// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlatform():Promise<string>;

export function GetVersion():Promise<Array<string>>;
