// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPlatform() {
  return window['go']['StartWindows']['Api']['GetPlatform']();
}

export function GetVersion() {
  return window['go']['StartWindows']['Api']['GetVersion']();
}
